Add `GetInverterInfo`
nielstron/pyfronius pull request #39
Opened 2021-08-22 11:07 UTC by farmio

This returns static infos about all inverters connected to one SolarNet.

TODO:

- [ ] add tests

2021-08-22 11:58 UTC, nielstron commented
Looks good :) As noted, please add some tests.

2021-08-22 21:19 UTC, nielstron requested changes
As noted, please stick to the renaming and refactoring convention of values provided by the API

2021-08-22 21:19 UTC, nielstron commented on pyfronius/__init__.py
> +                "CustomName": unescape(inverter_info.get("CustomName", ""))
Please stick to the renaming/refactoring pattern of converting keys to lower case + underscores and making the value a dictionary with value and unit (the latter being optional). This will simplify the integration with HA.

2021-08-22 21:19 UTC, nielstron commented on pyfronius/__init__.py
> +                **inverter_info,
see below, the keys returned by the API are non descriptive and camel cased, the package is expected to return descriptive lower case key value pairs.

2021-08-23 05:37 UTC, farmio commented on pyfronius/__init__.py
> +                "CustomName": unescape(inverter_info.get("CustomName", ""))
Alright. Please keep in mind that this is all static data - except for the status and error codes but these are not consistent over the 3 API versions. So I don't think this data should be used in the integration for other things than retrieving `custom_name` and `unique_id`.

2021-08-23 11:43 UTC, merged