Error handling
nielstron/pyfronius pull request #42
Opened 2021-08-29 22:04 UTC by farmio

Raise instances of `FroniusError` on invalid requests.
`Fronius.fetch()` suppresses these errors.

- not implemented api version endpoint
- empty response
- status code not `0`
- no body in response despite status code `0`

2021-08-30 12:55 UTC, nielstron requested changes
Looks good, just requires a small change :)

2021-08-30 12:55 UTC, nielstron commented on pyfronius/tests/test_web_v1.py
> +                self.fronius.current_storage_data()
if you assert that an error is raised, there is no need to keep "assertIn" statements

2021-08-30 12:56 UTC, nielstron commented
Also please check why the Travis build is failing

2021-08-30 13:33 UTC, farmio commented on pyfronius/tests/test_web_v1.py
> +                self.fronius.current_storage_data()
I kept it to test the BadStatusError.response was set correctly (which is used in `Fronius.fetch()`).

2021-08-30 15:42 UTC, nielstron commented on pyfronius/tests/test_web_v1.py
> +                self.fronius.current_storage_data()
nevermind, seems to have only been a display error in mobile GitHub...

2021-08-30 15:48 UTC, merged

2021-08-30 19:44 UTC, farmio commented
When this will be released I think it is safe to use `FroniusError` instead of `ConnectionError` at 
https://github.com/home-assistant/core/blob/dev/homeassistant/components/fronius/sensor.py#L208-L211
recurring errors for unavailable devices shouldn't be logged anyway 
from https://developers.home-assistant.io/docs/integration_quality_scale_index/
> Handles device/service unavailable. Log a warning once when unavailable, log once when reconnected.

2021-08-31 05:57 UTC, nielstron commented
Yes the excepted errors need to be changed to `FroniusError`.

 Note that the attribute `available` already ensures that we only log once on failed connection. However there is no log entry yet in case of successful reconnection and it seems that invalid responses are also not covered by the current setup.